/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package club.j3studios.a_login;

import club.j3studios.system.database.SQL;
import club.j3studios.system.utils.Tools;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author josne
 */
public class LoginSys extends javax.swing.JFrame {

    private LoginRegisterUtil logUtil;
    
    public LoginSys() {
        initComponents();
        logUtil = new LoginRegisterUtil();
        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("J3Studios C.A");
        avisoErroneo.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        button1 = new club.j3studios.system.utils.Button();
        textField = new club.j3studios.system.utils.TextField();
        passwordField = new club.j3studios.system.utils.PasswordField();
        avisoErroneo = new javax.swing.JLabel();
        button2 = new club.j3studios.system.utils.Button();
        avisoErroneo1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 10, 390, 140));

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user2.png"))); // NOI18N
        jLabel3.setText(" Correo Electrónico: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, -1, 50));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        jLabel4.setText(" Contraseña: ");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 150, 50));

        button1.setBackground(new java.awt.Color(60, 166, 251));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("INICIAR SESION");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button1.setShadowColor(new java.awt.Color(51, 51, 255));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, 40));

        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });
        textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldKeyPressed(evt);
            }
        });
        jPanel1.add(textField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 240, 40));

        passwordField.setToolTipText("");
        passwordField.setShowAndHide(true);
        passwordField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordFieldActionPerformed(evt);
            }
        });
        passwordField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passwordFieldKeyPressed(evt);
            }
        });
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 230, 240, 40));

        avisoErroneo.setForeground(new java.awt.Color(255, 0, 0));
        avisoErroneo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avisoErroneo.setText("¿No tienes una cuenta? Crea una...");
        jPanel1.add(avisoErroneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 380, 30));

        button2.setBackground(new java.awt.Color(153, 255, 255));
        button2.setForeground(new java.awt.Color(51, 51, 51));
        button2.setText("CREAR CUENTA");
        button2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button2.setShadowColor(new java.awt.Color(0, 204, 204));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, 160, 30));

        avisoErroneo1.setForeground(new java.awt.Color(255, 0, 0));
        avisoErroneo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avisoErroneo1.setText("¿No tienes una cuenta? Crea una...");
        jPanel1.add(avisoErroneo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 380, 390, 30));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoJ3.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 150));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("J3Studios");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 340, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WWW.J3STUDIOS.STORE");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 340, 30));

        jLabel7.setText("J3Studios © Copyright 2023");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 300, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Créditos");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 340, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("<html>¡A partir de tan solo <b>$9,99</b>!</html>");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 340, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Desarrollado por J3Studios C.A");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 340, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("¿Deseas adquirir la licencia de uso?");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 220, 330, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Ingresa a WWW.J3STUDIOS.STORE ahora");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 340, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Variedad de métodos de pagos disponibles para Venezuela!");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 340, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("¡Adquiere tu licencia mensual o anual!");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 340, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordFieldActionPerformed

    }//GEN-LAST:event_passwordFieldActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        performLogin();
    }//GEN-LAST:event_button1ActionPerformed

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed

    }//GEN-LAST:event_textFieldActionPerformed

    private void textFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            performLogin();
        }
    }//GEN-LAST:event_textFieldKeyPressed

    private void passwordFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordFieldKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            performLogin();
        }
    }//GEN-LAST:event_passwordFieldKeyPressed

    // REGISTER
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        new RegisterSys().setVisible(true);
        dispose();
    }//GEN-LAST:event_button2ActionPerformed
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new LoginSys().setVisible(true);
        });
    }
        
    @SuppressWarnings("deprecation")
    public void performLogin() {
               
        if (!textField.getText().isEmpty() && !passwordField.getText().isEmpty()) {
            String username = textField.getText();
            String password = new String(passwordField.getPassword());
                        
            ModelLogin data = new ModelLogin(username, password);
            try {
                ModelUser user = logUtil.login(data);
                if (user != null) {
                    new LoginSysLogged(user.getUserID()).setVisible(true);
                    dispose();
                    //return;
                    /*
                    if (this.checkLicense(username)) {
                        if (this.checkActiveLicense(licenseID)) {
                            new LoginSysLogged(idCuenta).setVisible(true);
                            dispose();
                            return;
                        }
                        new LoginSysLicenceExpire(idCuenta).setVisible(true);
                    } else {
                        new LoginSysLicence(idCuenta).setVisible(true);
                    }*/
                } else {
                    passwordField.setText("");
                    textField.setText("");
                    avisoErroneo.setText("Usuario o clave incorrecto, intenta de nuevo.");
                    Timer timer = new Timer(5000, (ActionEvent e) -> {
                        avisoErroneo.setText("");
                    });
                    timer.start();
                }
            } catch (SQLException e) {
                //showMessage(Message.MessageType.ERROR, "Error Login");
            }
        } else {
            avisoErroneo.setText("El campo de usuario/clave está vacío");
            Timer timer = new Timer(5000, (ActionEvent e) -> {
                avisoErroneo.setText("");
            });
            timer.start();
        }
    }
    
    public boolean login(String correo, String password) {		
        boolean response = false;        
        Connection con = SQL.conectar2();        
        String sql = "select correo, password from tb_cuentas where correo = '" + correo + "' and password = '" + password + "'";		
	Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                response = true;
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return response;
    }
    
    private Integer licenseID = 0;
    public static Integer idCuenta = 0;
    public boolean checkLicense(String correo) {		
        boolean response = false;        
        Connection con = SQL.conectar2();        
        String sql = "select * from tb_cuentas where correo = '" + correo + "'";		
	Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                idCuenta = rs.getInt("idCuenta");
                Integer id = rs.getInt("idLicense");
                if (id > 0) {
                    licenseID = rs.getInt("idLicense");
                    response = true;
                }
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return response;
    }
    
    public boolean checkActiveLicense (Integer licenseID) {		
        boolean response = false;        
        Connection con = SQL.conectar2();        
        String sql = "select * from tb_licencias where idLicense = '" + licenseID + "'";		
	Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String expireDate = rs.getString("expireDate");
                Date date = new Date();
                String fechaActual = new SimpleDateFormat("dd/MM/yyyy").format(date);
                Integer difFecha = this.diferenciaFechas(fechaActual, expireDate);
                if (difFecha >= 0) {
                    response = true;
                }
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return response;
    }
    
    private Integer diferenciaFechas(String fechaInicial, String fechaFinal){  
         String[] fechaI = fechaInicial.split("/");
         String[] fechaF = fechaFinal.split("/");
         
         Calendar cal = Calendar.getInstance();

         cal.set(Calendar.DAY_OF_MONTH, Integer.parseInt(fechaI[0]));
         cal.set(Calendar.MONTH, Integer.parseInt(fechaI[1]));
         cal.set(Calendar.YEAR, Integer.parseInt(fechaI[2]));
         Date firstDate = cal.getTime();
         
         cal.set(Calendar.DAY_OF_MONTH, Integer.parseInt(fechaF[0]));
         cal.set(Calendar.MONTH, Integer.parseInt(fechaF[1]));
         cal.set(Calendar.YEAR, Integer.parseInt(fechaF[2]));
         Date secondDate = cal.getTime();
         
         long diferencia = secondDate.getTime() - firstDate.getTime();
         Integer diferenciaFinal = Integer.valueOf(""+(diferencia/1000/60/60/24));
         
         return diferenciaFinal;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoErroneo;
    private javax.swing.JLabel avisoErroneo1;
    private club.j3studios.system.utils.Button button1;
    private club.j3studios.system.utils.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private club.j3studios.system.utils.PasswordField passwordField;
    private club.j3studios.system.utils.TextField textField;
    // End of variables declaration//GEN-END:variables
}
