/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package club.j3studios.a_login;

import club.j3studios.system.*;
import club.j3studios.system.database.SQL;
import club.j3studios.system.utils.Tools;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author josne
 */
public class LoginSysLogged extends javax.swing.JFrame {

    private Integer idCuenta;    
    private String nombre = "";
    private String razonSocial = "";
    private String licenseStatus = "";
    private String licenseExpire = "";
    
    public LoginSysLogged(Integer idCuenta) {
        this.idCuenta = idCuenta;
        initComponents();
        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("J3Studios C.A");
        
        loadInfo();
        updateText();
    }
    
    public void updateText(){
        txtNombre.setText(nombre);
        txtRazonSocial.setText(razonSocial);
        txtEstado.setText(licenseStatus);
        txtExpire.setText(licenseExpire);
        if (this.licenseStatus.equalsIgnoreCase("Inactiva")) {
            txtEstado.setForeground(Color.RED);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        button1 = new club.j3studios.system.utils.Button();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        txtRazonSocial = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txtExpire = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 390, 140));

        button1.setBackground(new java.awt.Color(60, 166, 251));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("INICIAR SISTEMA");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button1.setShadowColor(new java.awt.Color(51, 51, 255));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 350, 200, 60));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoJ3.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 150));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("J3Studios");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 310, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WWW.J3STUDIOS.STORE");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 310, 30));

        jLabel7.setText("J3Studios © 2023");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 300, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Créditos");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 310, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("<html>¡A partir de tan solo <b>$9,99</b>!</html>");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 310, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Desarrollado por J3Studios C.A");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 310, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("¿Deseas adquirir la licencia de uso?");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 220, 300, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Ingresa a WWW.J3STUDIOS.STORE ahora");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 310, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Variedad de métodos de pagos disponibles para Venezuela!");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 320, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("¡Adquiere tu licencia mensual o anual!");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 310, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 450));

        txtEstado.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtEstado.setForeground(new java.awt.Color(0, 74, 0));
        txtEstado.setText("ACTIVO");
        jPanel1.add(txtEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 140, 20));
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 140, 20));
        jPanel1.add(txtRazonSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 140, 20));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("Nombre: ");
        jPanel1.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 200, 140, 20));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel20.setText("Estado de la Licencia: ");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 140, 20));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel21.setText("Razón Social: ");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 230, 140, 20));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel23.setText("Fecha de Vencimiento: ");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 140, 20));
        jPanel1.add(txtExpire, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 140, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        if (licenseStatus.equalsIgnoreCase("Inactiva")) {
            if (this.checkLicense(idCuenta)) {
                new LoginSysLicenceExpire(idCuenta).setVisible(true);
            } else {
                new LoginSysLicence(idCuenta).setVisible(true);
            }
        } else {
            new LoginUser().setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_button1ActionPerformed
   
    public void loadInfo() {	       
        Connection con = SQL.conectar2();        
        String sql = "select * from tb_cuentas where idCuenta = '" + idCuenta + "'";		
	Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                nombre = rs.getString("nombre");
                razonSocial = rs.getString("razonSocial");
                loadLicense(rs.getInt("idLicense"));
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void loadLicense (Integer licenseID) { 
        Connection con = SQL.conectar2();        
        String sql = "select * from tb_licencias where idLicense = '" + licenseID + "'";		
	Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String expireDate = rs.getString("expireDate");
                Date date = new Date();
                String fechaActual = new SimpleDateFormat("dd/MM/yyyy").format(date);
                Integer difFecha = this.diferenciaFechas(fechaActual, expireDate);
                new Tools().debug("Diferencia fecha: " + difFecha);
                
                licenseStatus = "Inactiva";
                licenseExpire = "Renueva tu licencia!";
                if (difFecha >= 0) {
                    licenseStatus = "Activa";
                    licenseExpire = ""+difFecha+ " días restantes.";
                }
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    private Integer licenseID = 0;
    public boolean checkLicense(Integer idCuenta) {		
        boolean response = false;        
        Connection con = SQL.conectar2();        
        String sql = "select * from tb_cuentas where idCuenta = '" + idCuenta + "'";		
	Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                Integer id = rs.getInt("idLicense");
                if (id > 0) {
                    licenseID = rs.getInt("idLicense");
                    response = true;
                }
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return response;
    }
    
    public boolean checkActiveLicense (Integer licenseID) {		
        boolean response = false;        
        Connection con = SQL.conectar2();        
        String sql = "select * from tb_licencias where idLicense = '" + licenseID + "'";		
	Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String expireDate = rs.getString("expireDate");
                Date date = new Date();
                String fechaActual = new SimpleDateFormat("dd/MM/yyyy").format(date);
                Integer difFecha = this.diferenciaFechas(fechaActual, expireDate);
                if (difFecha >= 0) {
                    response = true;
                }
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return response;
    }
    
    private Integer diferenciaFechas(String fechaInicial, String fechaFinal){  
         String[] fechaI = fechaInicial.split("/");
         String[] fechaF = fechaFinal.split("/");
         
         Calendar cal = Calendar.getInstance();

         cal.set(Calendar.DAY_OF_MONTH, Integer.parseInt(fechaI[0]));
         cal.set(Calendar.MONTH, Integer.parseInt(fechaI[1]));
         cal.set(Calendar.YEAR, Integer.parseInt(fechaI[2]));
         Date firstDate = cal.getTime();
         
         cal.set(Calendar.DAY_OF_MONTH, Integer.parseInt(fechaF[0]));
         cal.set(Calendar.MONTH, Integer.parseInt(fechaF[1]));
         cal.set(Calendar.YEAR, Integer.parseInt(fechaF[2]));
         Date secondDate = cal.getTime();
         
         long diferencia = secondDate.getTime() - firstDate.getTime();
         Integer diferenciaFinal = Integer.valueOf(""+(diferencia/1000/60/60/24));
         
         return diferenciaFinal;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private club.j3studios.system.utils.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txtEstado;
    private javax.swing.JLabel txtExpire;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JLabel txtRazonSocial;
    // End of variables declaration//GEN-END:variables
}
