/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package club.j3studios.a_login;

import club.j3studios.system.database.SQL;
import club.j3studios.system.utils.Tools;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author josne
 */
public class RegisterSys extends javax.swing.JFrame {

    private RegisterVerifyCode verifyCode;
    private LoginRegisterUtil logUtil;
    
    public ModelUser getUser() {
        return user;
    }

    private ModelUser user;
    
    public RegisterSys() {
        initComponents();
        init();
        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setTitle("J3Studios C.A");
        avisoErroneo.setText("");
    }

    private void init(){
        logUtil = new LoginRegisterUtil();
        verifyCode = new RegisterVerifyCode();        
        verifyCode.addEventButtonOK((ActionEvent ae) -> {
            try {
                if (logUtil.verifyCodeWithUser(user.getUserID(), verifyCode.getInputCode())) {
                    logUtil.doneVerify(user.getUserID());
                    verifyCode.setVisible(false);
                    new LoginSys().setVisible(true);
                    dispose();
                } else {
                    verifyCode.txtAviso.setText("El código no es el correcto, verifica tu correo!");
                    verifyCode.txtAviso.setForeground(new Color(255, 0, 0));
                    Timer timer = new Timer(2500, (ActionEvent e) -> {
                        verifyCode.txtAviso.setForeground(new java.awt.Color(51, 51, 51));
                        verifyCode.txtAviso.setText("Revisa tu Email, recibiste un código de confirmación!");
                    });
                    timer.start();
                }
            } catch (SQLException e) {
                new Tools().debug("ERROR : EVENT OK BUTTON VERIFY CODE!");
            }
        });
    }
    
    private void sendMain (ModelUser user) {
        new Thread(() -> {
            ModelMessage ms = new ServiceMail().sendMain(user.getEmail(), user.getVerifyCode());
            if (ms.isSuccess()) {
                new Tools().debug("Abriendo panel Verify Code!");
                verifyCode.setVisible(true);
            } else {
                new Tools().debug("Error al intentar procesar el correo!");
            }
        }).start();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        button1 = new club.j3studios.system.utils.Button();
        txtCorreo = new club.j3studios.system.utils.TextField();
        txtPass = new club.j3studios.system.utils.PasswordField();
        avisoErroneo = new javax.swing.JLabel();
        button2 = new club.j3studios.system.utils.Button();
        avisoErroneo1 = new javax.swing.JLabel();
        txtNombre = new club.j3studios.system.utils.TextField();
        txtSocial = new club.j3studios.system.utils.TextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user2.png"))); // NOI18N
        jLabel3.setText("Empresa/Razón Social:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, 170, 50));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 390, 140));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/password.png"))); // NOI18N
        jLabel4.setText(" Contraseña: ");
        jLabel4.setToolTipText("");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 150, 50));

        button1.setBackground(new java.awt.Color(60, 166, 251));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("REGISTRARSE");
        button1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button1.setShadowColor(new java.awt.Color(51, 51, 255));
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        jPanel1.add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 340, 160, 40));

        txtCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoActionPerformed(evt);
            }
        });
        txtCorreo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCorreoKeyPressed(evt);
            }
        });
        jPanel1.add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 220, 40));

        txtPass.setToolTipText("");
        txtPass.setShowAndHide(true);
        txtPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPassActionPerformed(evt);
            }
        });
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        jPanel1.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 220, 40));

        avisoErroneo.setForeground(new java.awt.Color(255, 0, 0));
        avisoErroneo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avisoErroneo.setText("¿No tienes una cuenta? Crea una...");
        jPanel1.add(avisoErroneo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 380, 30));

        button2.setBackground(new java.awt.Color(153, 255, 255));
        button2.setForeground(new java.awt.Color(51, 51, 51));
        button2.setText("INICIAR SESION");
        button2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        button2.setShadowColor(new java.awt.Color(0, 204, 204));
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        jPanel1.add(button2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 160, 30));

        avisoErroneo1.setForeground(new java.awt.Color(255, 0, 0));
        avisoErroneo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        avisoErroneo1.setText("¿Ya tienes una cuenta? Ingresa!");
        jPanel1.add(avisoErroneo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 380, 390, 30));

        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 220, 40));

        txtSocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSocialActionPerformed(evt);
            }
        });
        txtSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSocialKeyPressed(evt);
            }
        });
        jPanel1.add(txtSocial, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 220, 40));

        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user2.png"))); // NOI18N
        jLabel16.setText(" Correo Electrónico: ");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, 50));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogoJ3.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 150));

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("J3Studios");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 350, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("WWW.J3STUDIOS.STORE");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 350, 30));

        jLabel7.setText("J3Studios © Copyright 2023");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 300, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Créditos");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 350, -1));

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("<html>¡A partir de tan solo <b>$9,99</b>!</html>");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 350, -1));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Desarrollado por J3Studios C.A");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 350, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("¿Deseas adquirir la licencia de uso?");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(3, 220, 340, -1));

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Ingresa a WWW.J3STUDIOS.STORE ahora");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 350, -1));

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Variedad de métodos de pagos disponibles para Venezuela!");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 350, -1));

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("¡Adquiere tu licencia mensual o anual!");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 350, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 450));

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/user2.png"))); // NOI18N
        jLabel17.setText("Nombre: ");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 150, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPassActionPerformed

    }//GEN-LAST:event_txtPassActionPerformed

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        this.performRegister();
    }//GEN-LAST:event_button1ActionPerformed

    private void txtCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoActionPerformed

    }//GEN-LAST:event_txtCorreoActionPerformed

    private void txtCorreoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCorreoKeyPressed
        
    }//GEN-LAST:event_txtCorreoKeyPressed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        
    }//GEN-LAST:event_txtPassKeyPressed

    // REGISTER
    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        new LoginSys().setVisible(true);
        dispose();
    }//GEN-LAST:event_button2ActionPerformed

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtSocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSocialActionPerformed

    private void txtSocialKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSocialKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSocialKeyPressed
    
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new RegisterSys().setVisible(true);
        });
    }*/
        
    @SuppressWarnings("deprecation")
    public void performRegister() {
        if (txtCorreo.getText().isEmpty() || txtPass.getText().isEmpty() || txtNombre.getText().isEmpty() || txtSocial.getText().isEmpty()) {
            avisoErroneo.setText("Deben estar todos los campos llenos!");
            return;
        }
        
        String email = txtCorreo.getText().trim();
        String password = String.valueOf(txtPass.getPassword());
        String nombre = txtNombre.getText().trim();
        String razonSocial = txtSocial.getText().trim();
        user = new ModelUser(0, email, password, nombre, razonSocial);         
        try {
            if (logUtil.checkDuplicateEmail(email)) {
                avisoErroneo.setText("El correo electronico ya está en uso!");
            } else {
                logUtil.insertUser(user);
                sendMain(user);
            }
        } catch (SQLException ex) {
            Logger.getLogger(RegisterSys.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public boolean login(String correo, String password) {		
        boolean response = false;        
        Connection con = SQL.conectar2();        
        String sql = "select correo, password from tb_cuentas where correo = '" + correo + "' and password = '" + password + "'";		
	Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                response = true;
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return response;
    }
    
    private Integer licenseID = 0;
    private Integer idCuenta = 0;
    public boolean checkLicense(String correo) {		
        boolean response = false;        
        Connection con = SQL.conectar2();        
        String sql = "select * from tb_cuentas where correo = '" + correo + "'";		
	Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                idCuenta = rs.getInt("idCuenta");
                Integer id = rs.getInt("idLicense");
                if (id > 0) {
                    licenseID = rs.getInt("idLicense");
                    response = true;
                }
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return response;
    }
    
    public boolean checkActiveLicense (Integer licenseID) {		
        boolean response = false;        
        Connection con = SQL.conectar2();        
        String sql = "select * from tb_licencias where idLicense = '" + licenseID + "'";		
	Statement st;
        try {
            st = con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String expireDate = rs.getString("expireDate");
                Date date = new Date();
                String fechaActual = new SimpleDateFormat("dd/MM/yyyy").format(date);
                Integer difFecha = this.diferenciaFechas(fechaActual, expireDate);
                new Tools().debug("Diferencia fecha: " + difFecha);
                if (difFecha >= 0) {
                    response = true;
                }
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
        return response;
    }
    
    private Integer diferenciaFechas(String fechaInicial, String fechaFinal){  
         String[] fechaI = fechaInicial.split("/");
         String[] fechaF = fechaFinal.split("/");
         
         Calendar cal = Calendar.getInstance();

         cal.set(Calendar.DAY_OF_MONTH, Integer.parseInt(fechaI[0]));
         cal.set(Calendar.MONTH, Integer.parseInt(fechaI[1]));
         cal.set(Calendar.YEAR, Integer.parseInt(fechaI[2]));
         Date firstDate = cal.getTime();
         
         cal.set(Calendar.DAY_OF_MONTH, Integer.parseInt(fechaF[0]));
         cal.set(Calendar.MONTH, Integer.parseInt(fechaF[1]));
         cal.set(Calendar.YEAR, Integer.parseInt(fechaF[2]));
         Date secondDate = cal.getTime();
         
         long diferencia = secondDate.getTime() - firstDate.getTime();
         Integer diferenciaFinal = Integer.valueOf(""+(diferencia/1000/60/60/24));
         
         return diferenciaFinal;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel avisoErroneo;
    private javax.swing.JLabel avisoErroneo1;
    private club.j3studios.system.utils.Button button1;
    private club.j3studios.system.utils.Button button2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private club.j3studios.system.utils.TextField txtCorreo;
    private club.j3studios.system.utils.TextField txtNombre;
    private club.j3studios.system.utils.PasswordField txtPass;
    private club.j3studios.system.utils.TextField txtSocial;
    // End of variables declaration//GEN-END:variables
}
